# Generated by Django 3.2.25 on 2025-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_proyecto_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='title',
        ),
        migrations.AddField(
            model_name='empleado',
            name='salary',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empleadoproyecto',
            name='bonus_pay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
