# Generated by Django 3.2.25 on 2025-07-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20250703_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implemento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
