# Generated by Django 3.2.25 on 2025-07-06 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_implemento_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facturacapacitacion',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='facturaempleado',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
