# Generated by Django 3.2.25 on 2025-07-07 03:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250706_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('detalle', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.capacitacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
            ],
        ),
        migrations.RemoveField(
            model_name='facturaempleado',
            name='worker',
        ),
        migrations.DeleteModel(
            name='FacturaCapacitacion',
        ),
        migrations.DeleteModel(
            name='FacturaEmpleado',
        ),
    ]
