# Generated by Django 3.2.25 on 2025-07-08 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250706_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='profesion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app.profesion'),
            preserve_default=False,
        ),
    ]
