# Generated by Django 3.2.25 on 2025-07-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250708_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesion',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
