# Generated by Django 3.2.25 on 2025-07-07 05:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20250706_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.afp')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empleado')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pago')),
            ],
        ),
        migrations.CreateModel(
            name='PagoInsumoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.capacitacion')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.pago')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagosueldo',
            name='worker',
        ),
        migrations.RenameField(
            model_name='pagoimplemento',
            old_name='id_implement',
            new_name='implemento',
        ),
        migrations.RenameField(
            model_name='pagovehiculo',
            old_name='vehicle',
            new_name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='pagoimplemento',
            name='id_pay',
        ),
        migrations.RemoveField(
            model_name='pagovehiculo',
            name='id_pay',
        ),
        migrations.DeleteModel(
            name='EmpleadoCapacitacion',
        ),
        migrations.DeleteModel(
            name='PagoBien',
        ),
        migrations.DeleteModel(
            name='PagoSueldo',
        ),
        migrations.AddField(
            model_name='pagoimplemento',
            name='pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pagoinsumoservicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagovehiculo',
            name='pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pago'),
            preserve_default=False,
        ),
    ]
