# Generated by Django 3.2.25 on 2025-07-07 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20250707_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoimplemento',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pago'),
        ),
    ]
