# Generated by Django 3.2.25 on 2025-07-08 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profesion_name'),
        ('app', '0008_alter_pagoimplemento_pago'),
    ]

    operations = [
    ]
