# Generated by Django 3.2.25 on 2025-07-11 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20250708_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implemento',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empleado'),
        ),
    ]
